package com.is.findyourplace.System;// Generated by Selenium IDE
import com.is.findyourplace.persistence.repository.UtenteRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.time.Duration;
import java.util.*;

@SpringBootTest()
public class TC11Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Autowired
  private UtenteRepository utenteRepository;
  @Test
  public void tC1111() {
    String username = "davidecalif";
    if(utenteRepository.existsByUsername(username))
      fail("L'Username usato in questo test esiste già!");
    String email = "davidecalifano03@gmail.com";
    if(utenteRepository.existsByEmail(email))
      fail("L'Email usata in questo test esiste già!");

    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1392));
    driver.findElement(By.id("nameSignup")).sendKeys("Davide");
    driver.findElement(By.id("lastnameSignup")).sendKeys("Califano");
    driver.findElement(By.id("phoneSignup")).sendKeys("3274865145");
    driver.findElement(By.id("birthDateSignup")).sendKeys("04-06-2001");
    driver.findElement(By.id("usernameSignup")).sendKeys(username);
    driver.findElement(By.id("emailSignup")).sendKeys(email);
    driver.findElement(By.cssSelector(".form-field:nth-child(8)")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DavidCalif03!");
    driver.findElement(By.id("passwordSignup2")).sendKeys("DavidCalif03!");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();

    new WebDriverWait(driver, Duration.ofSeconds(5))
            .until(ExpectedConditions.urlToBe("http://localhost:8080/"));
    utenteRepository.deleteById(utenteRepository.findByUsername(username).getIdUtente());
    assertEquals("http://localhost:8080/", driver.getCurrentUrl());
    //driver.close();
  }
  @Test
  public void tC111() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).sendKeys("3246533265");
    driver.findElement(By.id("birthDateSignup")).sendKeys("04-06-2001");
    driver.findElement(By.id("usernameSignup")).sendKeys("Dada");
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@Gmail.com");
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "L'username non rispecchia il formato corretto. Riprovare!");
    //driver.close();
  }
  @Test
  public void tC112() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).sendKeys("3216599845");
    driver.findElement(By.id("birthDateSignup")).sendKeys("03-04-1970");
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioligmail.com");
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "L'email non rispecchia il formato corretto. Riprovare!");
    //driver.close();
  }
  @Test
  public void tC113() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    driver.findElement(By.id("birthDateSignup")).sendKeys("05-03-1992");
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG");
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "La password non rispecchia il formato corretto. Riprovare!");
    //driver.close();
  }
  @Test
  public void tC114() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    driver.findElement(By.id("birthDateSignup")).sendKeys("24-05-2002");
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).sendKeys("Diegone12!");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Le password inserite non sono uguali. Riprovare!");
    //driver.close();
  }
  @Test
  public void tC115() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).sendKeys("Die(g)o");
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.id("birthDateSignup")).sendKeys("05-06-2001");
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Nome e/o Cognome non validi!");
    //driver.close();
  }
  @Test
  public void tC116() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli*!");
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    driver.findElement(By.id("birthDateSignup")).sendKeys("25-05-2000");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Nome e/o Cognome non validi!");
    //driver.close();
  }
  @Test
  public void tC117()  {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    js.executeScript("document.getElementById('birthDateSignup').setAttribute('type', 'text')");
    driver.findElement(By.id("birthDateSignup")).sendKeys("03-08-199F8");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Data di nascita non valida. Riprovare!");
    //driver.close();
  }
  @Test
  public void tC118() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    driver.findElement(By.id("birthDateSignup")).sendKeys("25-05-2026");
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertFalse(driver.findElements(By.id("dataNascitaSError")).isEmpty());
    //driver.close();
  }
  @Test
  public void tC119() {
    String username = "Dadone";
    if(utenteRepository.existsByUsername(username))
      fail("L'Username usato in questo test esiste già!");
    String email = "DiegoGiulioli@gmail.com";
    if(utenteRepository.existsByEmail(email))
      fail("L'Email usata in questo test esiste già!");

    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("usernameSignup")).sendKeys(username);
    driver.findElement(By.id("emailSignup")).sendKeys(email);
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("birthDateSignup")).sendKeys("23-02-2000");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();

    new WebDriverWait(driver, Duration.ofSeconds(5))
            .until(ExpectedConditions.urlToBe("http://localhost:8080/"));
    utenteRepository.deleteById(utenteRepository.findByUsername(username).getIdUtente());
    assertEquals("http://localhost:8080/", driver.getCurrentUrl());
    //driver.close();
  }
  @Test
  public void tC1110() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).sendKeys("3276e548r679");
    driver.findElement(By.id("birthDateSignup")).sendKeys("25-05-1997");
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Numero di telefono non valido. Riprovare!");
    //driver.close();
  }
}
