package com.is.findyourplace.System;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;


public class TC11Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC1111() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1392));
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).sendKeys("Davide");
    driver.findElement(By.cssSelector("#section-Signup .form-field:nth-child(3)")).click();
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("Califano");
    driver.findElement(By.id("phoneSignup")).click();
    driver.findElement(By.id("phoneSignup")).sendKeys("3274865145");
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).sendKeys("04-06-2001");
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).sendKeys("davidecalif");
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).sendKeys("davidecalifano03@gmail.com");
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passEyeSignup1")).click();
    driver.findElement(By.cssSelector(".form-field:nth-child(8)")).click();
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("section-Signup")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DavidCalif03!");
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).sendKeys("DavidCalif03!");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    //driver.close();
  }
  @Test
  public void tC111() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).click();
    driver.findElement(By.id("phoneSignup")).sendKeys("3246533265");
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).sendKeys("04-06-2001");
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).sendKeys("Dada");
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@Gmail.com");
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passEyeSignup1")).click();
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("section-Signup")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passEyeSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertThat(driver.switchTo().alert().getText(), is("L\'username non rispecchia il formato corretto. Riprovare!"));
    //driver.close();
  }
  @Test
  public void tC112() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).click();
    driver.findElement(By.id("phoneSignup")).sendKeys("3216599845");
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).sendKeys("03-04-1970");
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioligmail.com");
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertThat(driver.switchTo().alert().getText(), is("L\'email non rispecchia il formato corretto. Riprovare!"));
    //driver.close();
  }
  @Test
  public void tC113() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).click();
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).sendKeys("05-03-1992");
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("section-Signup")).click();
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG");
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertThat(driver.switchTo().alert().getText(), is("La password non rispecchia il formato corretto. Riprovare!"));
    //driver.close();
  }
  @Test
  public void tC114() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).click();
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).sendKeys("24-05-2002");
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).sendKeys("Diegone12!");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Le password inserite non sono uguali. Riprovare!"));
    //driver.close();
  }
  @Test
  public void tC115() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).click();
    {
      WebElement element = driver.findElement(By.id("nameSignup"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("section-Signup")).click();
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).sendKeys("Die(g)o");
    driver.findElement(By.id("lastnameSignup")).click();
    {
      WebElement dragged = driver.findElement(By.id("lastnameSignup"));
      WebElement dropped = driver.findElement(By.id("phoneSignup"));
      Actions builder = new Actions(driver);
      builder.dragAndDrop(dragged, dropped).perform();
    }
    driver.findElement(By.id("phoneSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).sendKeys("05-06-2001");
    driver.findElement(By.id("section-Signup")).click();
    {
      WebElement dragged = driver.findElement(By.id("phoneSignup"));
      WebElement dropped = driver.findElement(By.id("emailSignup"));
      Actions builder = new Actions(driver);
      builder.dragAndDrop(dragged, dropped).perform();
    }
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("phoneSignup")).click();
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Nome e/o Cognome non validi!"));
    //driver.close();
  }
  @Test
  public void tC116() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli*!");
    driver.findElement(By.id("phoneSignup")).click();
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).sendKeys("25-05-2000");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Nome e/o Cognome non validi!"));
    //driver.close();
  }
  @Test
  public void tC117()  {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).click();
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).click();
    js.executeScript("document.getElementById('birthDateSignup').setAttribute('type', 'text')");
    driver.findElement(By.id("birthDateSignup")).sendKeys("03-08-199F8");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Data di nascita non valida. Riprovare!"));
    //driver.close();
  }
  @Test
  public void tC118() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).click();
    driver.findElement(By.id("phoneSignup")).sendKeys("3276548679");
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).sendKeys("25-05-2026");
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passEyeSignup1")).click();
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertFalse(driver.findElements(By.id("futureDateError")).isEmpty());
    //driver.close();
  }
  @Test
  public void tC119() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).sendKeys("23-02-2000");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    //driver.close();
  }
  @Test
  public void tC1110() {
    driver.get("http://localhost:8080/accountAuth");
    driver.manage().window().setSize(new Dimension(2552, 1390));
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("usernameSignup")).click();
    driver.findElement(By.id("usernameSignup")).sendKeys("Dadone");
    driver.findElement(By.id("nameSignup")).click();
    driver.findElement(By.id("nameSignup")).click();
    {
      WebElement element = driver.findElement(By.id("nameSignup"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("nameSignup")).sendKeys("Diego");
    driver.findElement(By.id("lastnameSignup")).click();
    driver.findElement(By.id("lastnameSignup")).sendKeys("Giulioli");
    driver.findElement(By.id("phoneSignup")).click();
    driver.findElement(By.id("phoneSignup")).sendKeys("3276e548r679");
    driver.findElement(By.id("birthDateSignup")).click();
    driver.findElement(By.id("birthDateSignup")).sendKeys("25-05-1997");
    driver.findElement(By.id("emailSignup")).click();
    driver.findElement(By.id("emailSignup")).sendKeys("DiegoGiulioli@gmail.com");
    driver.findElement(By.id("passwordSignup1")).click();
    driver.findElement(By.id("passwordSignup1")).sendKeys("DiegoG12!");
    driver.findElement(By.id("passwordSignup2")).click();
    driver.findElement(By.id("passwordSignup2")).sendKeys("DiegoG12!");
    driver.findElement(By.cssSelector(".form-submitButton:nth-child(10)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Numero di telefono non valido. Riprovare!"));
    //driver.close();
  }
}
