package com.is.findyourplace.System;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.*;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class TF3_1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC311() {
    driver.get("http://localhost:8080/");
    Actions move = new Actions(driver);
    WebElement element;
    Action action;
    driver.manage().window().setSize(new Dimension(2576, 1416));
    element = driver.findElement(By.id("map"));
    action =  move.dragAndDropBy(element, -1000, 0).build();
    action.perform();
    driver.findElement(By.id("map")).click();
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    new WebDriverWait(driver, Duration.ofSeconds(20))
            .until(ExpectedConditions.textToBePresentInElementLocated(By.id("longitudeError"),"Coordinate non valide!"));

    assertFalse( driver.findElements(By.id("longitudeError")).isEmpty() || driver.findElements(By.id("latitudeError")).isEmpty());
    //driver.close();
  }
  @Test
  public void tC312() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.id("map")).click();
    js.executeScript("document.getElementById('raggio').setAttribute('type', 'text')");
    driver.findElement(By.id("raggio")).sendKeys("ff");
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Raggio non valido!");
    //driver.close();
  }
  @Test
  public void tC313() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.id("map")).click();
    driver.findElement(By.id("costoVita")).click();
    js.executeScript("document.getElementById('costoM').setAttribute('value', 'ff')");
    driver.findElement(By.id("costoM")).click();
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Costo Vita non valido!");
    //driver.close();
  }
  @Test
  public void tC314() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.id("map")).click();
    js.executeScript("document.getElementById('dangerMax').setAttribute('type', 'text')");
    driver.findElement(By.id("dangerMax")).sendKeys("ff");
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Pericolosità massima non valida!");
    //driver.close();
  }
  @Test
  public void tC315() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.id("map")).click();
    js.executeScript("document.getElementById('numAbitantiMax').setAttribute('type', 'text')");
    driver.findElement(By.id("numAbitantiMax")).sendKeys("ff");
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Numero abitanti massimo non valido!");
    //driver.close();
  }
  @Test
  public void tC316() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.id("map")).click();
    js.executeScript("document.getElementById('numAbitantiMin').setAttribute('type', 'text')");
    driver.findElement(By.id("numAbitantiMin")).sendKeys("ff");
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Numero abitanti minimo non valido!");
    //driver.close();
  }
  @Test
  public void tC317() {
    driver.get("http://localhost:8080/");
    Actions move = new Actions(driver);
    WebElement slider;
    Action action;
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.id("map")).click();
    slider = driver.findElement(By.id("numAbitantiMin"));
    action =  move.dragAndDropBy(slider, 500, 0).build();
    action.perform();
    slider = driver.findElement(By.id("numAbitantiMax"));
    action =  move.dragAndDropBy(slider, -700, 0).build();
    action.perform();
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Numero abitanti minimo maggiore del massimo!");
    //driver.close();
  }
  @Test
  public void tC318() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.id("map")).click();
    js.executeScript("document.getElementById('numNegoziMin').setAttribute('type', 'text')");
    driver.findElement(By.id("numNegoziMin")).sendKeys("ff");
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Numero negozi minimo non valido!");
    //driver.close();
  }
  @Test
  public void tC319() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.id("map")).click();
    js.executeScript("document.getElementById('numRistorantiMin').setAttribute('type', 'text')");
    driver.findElement(By.id("numRistorantiMin")).sendKeys("ff");
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Numero ristoranti minimo non valido!");
    //driver.close();
  }
  @Test
  public void tC3110() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.id("map")).click();
    js.executeScript("document.getElementById('numScuoleMin').setAttribute('type', 'text')");
    driver.findElement(By.id("numScuoleMin")).sendKeys("ff");
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    assertEquals(driver.switchTo().alert().getText(),
            "Numero scuole minimo non valido!");
    //driver.close();
  }
  @Test
  public void tC3111() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.id("map")).click();
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    new WebDriverWait(driver, Duration.ofSeconds(120))
            .until(ExpectedConditions.titleIs("Risultati Ricerca | FindYourPlace"));

    assertEquals("Risultati Ricerca | FindYourPlace", driver.getTitle());
    //driver.close();
  }
  @Test
  public void tC3112() {
    driver.get("http://localhost:8080/");
    Actions move = new Actions(driver);
    WebElement slider;
    Action action;
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.id("map")).click();
    slider = driver.findElement(By.id("raggio"));
    action =  move.dragAndDropBy(slider, -400, 0).build();
    action.perform();
    driver.findElement(By.id("costoVita")).click();
    {
      WebElement dropdown = driver.findElement(By.id("costoVita"));
      dropdown.findElement(By.xpath("//option[. = 'MEDIO']")).click();
    }
    slider = driver.findElement(By.id("dangerMax"));
    action =  move.dragAndDropBy(slider, 500, 0).build();
    action.perform();
    slider = driver.findElement(By.id("numAbitantiMin"));
    action =  move.dragAndDropBy(slider, -500, 0).build();
    action.perform();
    slider = driver.findElement(By.id("numAbitantiMax"));
    action =  move.dragAndDropBy(slider, 500, 0).build();
    action.perform();
    slider = driver.findElement(By.id("numNegoziMin"));
    action =  move.dragAndDropBy(slider, -500, 0).build();
    action.perform();
    slider = driver.findElement(By.id("numRistorantiMin"));
    action =  move.dragAndDropBy(slider, -500, 0).build();
    action.perform();
    slider = driver.findElement(By.id("numScuoleMin"));
    action =  move.dragAndDropBy(slider, -500, 0).build();
    action.perform();
    driver.findElement(By.cssSelector(".form-submitButton")).click();
    new WebDriverWait(driver, Duration.ofSeconds(120))
            .until(ExpectedConditions.titleIs("Risultati Ricerca | FindYourPlace"));

    assertEquals("Risultati Ricerca | FindYourPlace", driver.getTitle());
    //driver.close();
  }
}
