name: Maven CI/CD

on:
  push:
    branches: [ main, Pietro ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
            host port: 3306
            container port: 3306
            character set server: 'utf8'
            collation server: 'utf8_general_ci'
            mysql version: '8.0'
            mysql database: 'FindYourPlace'
            mysql root password: 'password'
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Run (J)Unit tests
        run: mvn clean test